# Default configuration file; do not edit this file, but the file .S-config.sh
# in your home directory. The latter gets created on the very first execution
# of some benchmark script (even if only the option -h is passed to the script).

# Set to yes if you want to use SCSI_DEBUG; this will override your
# possible choice for TEST_PARTITION below, and will set BASE_DIR too,
# automatically, overriding your possible choice for BASE_DIR below.
SCSI_DEBUG=no

# Set the following parameter if you want to perform tests on a given
# partition. The partition must contain a mounted filesystem. All test
# files will be created in that filesystem. BASE_DIR will be built
# automatically, overriding your possible choice below.
TEST_PARTITION=

# Directory containing files read/written during benchmarks.
# The path "$PWD/../" points to S root directory.
BASE_DIR=$PWD/../workfiles

# Next parameter contains the names of the devices the test files are
# on (devices may be more than one in case of a RAID
# configuration). Those devices are the ones for which, e.g., the I/O
# scheduler is changed, if you do ask the benchmarks to select the
# scheduler(s) to use. These devices are detected automatically.  If
# automatic detection does not work, or is not wat you want, then just
# reassign the value of DEVS.
#
# For example: DEVS=sda.
DEVS=

# Size of (each of) the files to create for reading/writing, in
# MiB. If left empty, then automatically set to the maximum value that
# guarantees that at most 50% of the free space is used, or left to
# the value used in last file creation, if lower than the latter
# threshold.  For random I/O with rotational devices, consider that
# the size of the files may heavily influence throughput and, in
# general, service properties.
#
# Change at your will, if you prefer a different value.
FILE_SIZE_MB=

# Portion, in 1M blocks, to read for each file, used only in
# fairness.sh; make sure it is not larger than $FILE_SIZE_MB
NUM_BLOCKS=2000

# If equal to 1, tracing is enabled during each test
TRACE=0

# The kernel-development benchmarks expect a repository in the
# following directory. In particular, they play with v4.0, v4.1 and
# v4.2, so they expect these versions to be present.
KERN_DIR=$BASE_DIR/linux.git-for_kern_dev_benchmarks
# If no repository is found in the above directory, then a repository
# is cloned therein. The source URL is stored in the following
# variable.
KERN_REMOTE=https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git

# NCQ queue depth, if undefined then no script will change the current value
NCQ_QUEUE_DEPTH=

# Mail-report parameters. A mail transfer agent (such as msmtp) and a mail
# client (such as mailx) must be installed to be able to send mail reports.
# The sender e-mail address will be the one configured as default in the
# mail client itself.
MAIL_REPORTS=0
MAIL_REPORTS_RECIPIENT=
